kind: Template
apiVersion: v1
metadata:
  name: app-template
labels:
  template: app-template

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      generation: 3
      labels:
        app: ${APP_NAME}
        name: ${APP_NAME}
      annotations:
        openshift.io/image.insecureRepository: "true"
    spec:
      tags:
        - name: release
          from:
            kind: DockerImage
            name: ${DOCKER_IMAGE}
          generation: 3
          importPolicy:
            insecure: true
          referencePolicy:
            type: Local
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-service-account
      labels:
        app: ${APP_NAME}
        name: ${APP_NAME}
    imagePullSecrets:
      - name: docker-pull-secret
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        name: ${APP_NAME}
    spec:
      ports:
        - name: 8401-tcp
          protocol: TCP
          port: 8401
          targetPort: 8401
      selector:
        deploymentconfig: ${APP_NAME}
      type: ClusterIP
      sessionAffinity: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        name: ${APP_NAME}
    spec:
      replicas: 2
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      strategy:
        type: Rolling
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 240
          maxUnavailable: 25%
          maxSurge: 25%
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            name: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: ${APP_NAME}-service-account
          serviceAccout: ${APP_NAME}-service-account
          containers:
            - name: ${APP_NAME}
              image: ${DOCKER_IMAGE}
              resources:
                requests:
                  cpu: 50m
                limits:
                  cpu: 500m
                  memory: 512Mi
              ports:
                - containerPort: 8401
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                  - cat
                  - /tmp/health
                initialDelaySeconds: 20
                timeoutSeconds: 2
              env:
                - name: SPRING_APPLICATION_JSON
                  valueFrom:
                    secretKeyRef:
                      name: ${APP_NAME}-properties
                      key: property-overrides
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:release
parameters:
  - name: APP_NAME
    displayName: 'Application name. All lowercase'
    description: 'A short name, like demo-app'
    required: true
  - name: DOCKER_IMAGE
    displayName: 'Docker Image'
    description: 'The fully qualified docker image name'
    required: true